def use_module(bld):
    sources = bld.path.ant_glob('src/**/*.xc')
    bld.env.XCC_FLAGS.append('-Os')
    bld.module(
        source=sources,
        includes=['api'],
        depends_on=['lib_xassert(>=3.0.0)', 'lib_logging(>=2.1.0)'],
        version='4.0.1')
