# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_i2c
project: '{{lib_name}}'
title: '{{lib_name}}: I²C library'
version: 6.4.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_i2c.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-004927-UG
  doxygen_projects:
    lib_i2c:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_i2c.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007006-SM
